image:
  tag: 12345

baseDomains:
  - portal.example.com
  - portal2.example.com

crdGatewayApiUrl: https://api.example.com

trust:
  portal:
    baseDomains: "portal.example.com,portal2.example.com"
    authDomain: https://auth.example.com
    discoveryEndpoint: https://auth.example.com/.well-known/openid-configuration
    loginAudience: 12345
    oidcClientSecretName: portal
