image:
  name: ghcr.io/openmfp/portal
  pullPolicy: IfNotPresent
  pullSecret: github

deployment:
  maxUnavailable: 0
  maxSurge: 5

port: 8080

istio:
  enabled: true

externalSecrets:
  enabled: true

http:
  protocol: https

importContent: true

validWebcomponentUrls: ".?"