export const FRAME_OPTIONS_INJECTION_TOKEN = 'FRAME_OPTIONS';
export const AUTH_CALLBACK_INJECTION_TOKEN = 'AUTH_CALLBACK';
export const TENANT_PROVIDER_INJECTION_TOKEN = 'TENANT_PROVIDER';
export const PORTAL_CONTEXT_INJECTION_TOKEN = 'FRAME_CONTEXT';
export const ENTITY_CONTEXT_INJECTION_TOKEN = 'ENTITY_CONTEXT';
export const SERVICE_PROVIDER_INJECTION_TOKEN = 'SERVICE_PROVIDER';
export const FEATURE_TOGGLES_INJECTION_TOKEN = 'FEATURE_TOGGLES';
export const HEALTH_CHECKER_INJECTION_TOKEN = 'HEALTH_CHECKER';
