apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
  - {{ .Release.Namespace }}/gateway
  hosts:
  {{ range $domainName := .Values.baseDomains }}
  - {{ $domainName }}
  {{- range $key, $idp := $.Values.trust }}
  - {{ $key }}.{{ $domainName }}
  {{- end }}
  {{- end }}
  http:
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      - '*'
      allowMethods:
      - GET
      - POST
      - PUT
      - DELETE
    route:
    - destination:
        host: {{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 8080
