name: pipe
on: [push]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipe:
    uses: openmfp/gha/.github/workflows/pipeline-node-app.yml@main
    secrets: inherit
    with:
      imageTagName: ghcr.io/openmfp/portal
      componentVersionKey: hackathon-portal
      release_branch: hackathon-portal