name: pipe
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipe:
    uses: openmfp/gha/.github/workflows/pipeline-node-app.yml@main
    secrets: inherit
    with:
      imageTagName: ghcr.io/openmfp/portal
      componentVersionKey: portal
      repoVersionUpdate: openmfp/helm-charts
